// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoomRentalManagerServer.Infrastructure.Data;

#nullable disable

namespace RoomRentalManagerServer.Infrastructure.Migrations
{
    [DbContext(typeof(RoomRentalManagerServerDbContext))]
    [Migration("20250304133820_Create_Contract_20250304")]
    partial class Create_Contract_20250304
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoomRentalManagerServer.Domain.ModelEntities.Contracts.Contract", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("CreatorUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("creatorUser");

                    b.Property<decimal>("DepositAmout")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("depositAmout");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("endDate");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monthlyRent");

                    b.Property<long>("RoomRentalId")
                        .HasColumnType("bigint")
                        .HasColumnName("roomRentalId");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("startDate");

                    b.Property<int>("StatusContract")
                        .HasColumnType("int")
                        .HasColumnName("statusContract");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenantId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UpdaterUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updaterUser");

                    b.HasKey("Id");

                    b.ToTable("contract");
                });

            modelBuilder.Entity("RoomRentalManagerServer.Domain.ModelEntities.ImageDescriptions.ImagesDescription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdDate");

                    b.Property<string>("CreatorUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("creatorUser");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("image");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("imageFileName");

                    b.Property<string>("ImageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("imageType");

                    b.Property<string>("LastUpdateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lastUpdateUser");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedDate");

                    b.HasKey("Id");

                    b.ToTable("image_descriptions");
                });

            modelBuilder.Entity("RoomRentalManagerServer.Domain.ModelEntities.RoomRentals.RoomRental", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("Area")
                        .HasColumnType("float")
                        .HasColumnName("area");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdDate");

                    b.Property<string>("CreatorUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("creatorUser");

                    b.PrimitiveCollection<string>("ImagesDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("images");

                    b.Property<string>("LastUpdateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lsatUpdateUser");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<double>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int")
                        .HasColumnName("roomNumber");

                    b.Property<int>("RoomType")
                        .HasColumnType("int")
                        .HasColumnName("roomType");

                    b.Property<int>("StatusRoom")
                        .HasColumnType("int")
                        .HasColumnName("statusRoom");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedDate");

                    b.HasKey("Id");

                    b.ToTable("roomrental");
                });

            modelBuilder.Entity("RoomRentalManagerServer.Domain.ModelEntities.User.Users", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("BikeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bikeId");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("dateofbirth");

                    b.Property<long>("DistrictId")
                        .HasColumnType("bigint")
                        .HasColumnName("districtId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gender");

                    b.Property<long>("IDCard")
                        .HasColumnType("bigint")
                        .HasColumnName("idCard");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("job");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<long>("ProvinceId")
                        .HasColumnType("bigint")
                        .HasColumnName("provinceId");

                    b.Property<int>("RoleGroupId")
                        .HasColumnType("int")
                        .HasColumnName("roleGroupId");

                    b.Property<long>("WardId")
                        .HasColumnType("bigint")
                        .HasColumnName("wardId");

                    b.HasKey("Id");

                    b.ToTable("user");
                });
#pragma warning restore 612, 618
        }
    }
}
