// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RoomRentalManagerServer.Infrastructure.Data;

#nullable disable

namespace RoomRentalManagerServer.Infrastructure.Migrations
{
    [DbContext(typeof(RoomRentalManagerServerDbContext))]
    [Migration("20250401070653_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoomRentalManagerServer.Domain.ModelEntities.Contracts.Contract", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("CreatorUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creatorUser");

                    b.Property<decimal>("DepositAmout")
                        .HasColumnType("numeric")
                        .HasColumnName("depositAmout");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("endDate");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("numeric")
                        .HasColumnName("monthlyRent");

                    b.Property<long>("RoomRentalId")
                        .HasColumnType("bigint")
                        .HasColumnName("roomRentalId");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startDate");

                    b.Property<int>("StatusContract")
                        .HasColumnType("integer")
                        .HasColumnName("statusContract");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenantId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UpdaterUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updaterUser");

                    b.HasKey("Id");

                    b.ToTable("contract");
                });

            modelBuilder.Entity("RoomRentalManagerServer.Domain.ModelEntities.Equipments.Equipment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("CreatorUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creatorUser");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("LastUpdateUser")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastUpdateUser");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.ToTable("equipment");
                });

            modelBuilder.Entity("RoomRentalManagerServer.Domain.ModelEntities.ImageDescriptions.ImagesDescription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdDate");

                    b.Property<string>("CreatorUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creatorUser");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("image");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("imageFileName");

                    b.Property<string>("ImageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("imageType");

                    b.Property<string>("LastUpdateUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastUpdateUser");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedDate");

                    b.HasKey("Id");

                    b.ToTable("image_descriptions");
                });

            modelBuilder.Entity("RoomRentalManagerServer.Domain.ModelEntities.Invoices.Invoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ContractId")
                        .HasColumnType("bigint")
                        .HasColumnName("contractId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("CreatorUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creatorUser");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dueDate");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invoiceDate");

                    b.Property<string>("LastUpdateUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastUpdateUser");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("invoiceStatus");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("totalAmount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.ToTable("invoice");
                });

            modelBuilder.Entity("RoomRentalManagerServer.Domain.ModelEntities.PaymentAmount.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("numeric")
                        .HasColumnName("AmountPaid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("invoiceId");

                    b.Property<DateTime>("LastUpdateUser")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastUpdateUser");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<decimal>("PaymentDate")
                        .HasColumnType("numeric")
                        .HasColumnName("paymentDate");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer")
                        .HasColumnName("paymentMethod");

                    b.Property<int>("StatusPayment")
                        .HasColumnType("integer")
                        .HasColumnName("statusPayment");

                    b.HasKey("Id");

                    b.ToTable("payment");
                });

            modelBuilder.Entity("RoomRentalManagerServer.Domain.ModelEntities.RoomEquipments.RoomEquipment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<long>("EquipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("equipmentId");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("roomId");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.ToTable("roomEquipment");
                });

            modelBuilder.Entity("RoomRentalManagerServer.Domain.ModelEntities.RoomRentals.RoomRental", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Area")
                        .HasColumnType("double precision")
                        .HasColumnName("area");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdDate");

                    b.Property<string>("CreatorUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creatorUser");

                    b.PrimitiveCollection<List<int>>("ImagesDescription")
                        .HasColumnType("integer[]")
                        .HasColumnName("images");

                    b.Property<string>("LastUpdateUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lsatUpdateUser");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("integer")
                        .HasColumnName("roomNumber");

                    b.Property<int>("RoomType")
                        .HasColumnType("integer")
                        .HasColumnName("roomType");

                    b.Property<int>("StatusRoom")
                        .HasColumnType("integer")
                        .HasColumnName("statusRoom");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedDate");

                    b.HasKey("Id");

                    b.ToTable("roomrental");
                });

            modelBuilder.Entity("RoomRentalManagerServer.Domain.ModelEntities.User.Users", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("BikeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bikeId");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateofbirth");

                    b.Property<long>("DistrictId")
                        .HasColumnType("bigint")
                        .HasColumnName("districtId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<long>("IDCard")
                        .HasColumnType("bigint")
                        .HasColumnName("idCard");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<long>("ProvinceId")
                        .HasColumnType("bigint")
                        .HasColumnName("provinceId");

                    b.Property<int>("RoleGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("roleGroupId");

                    b.Property<long>("WardId")
                        .HasColumnType("bigint")
                        .HasColumnName("wardId");

                    b.HasKey("Id");

                    b.ToTable("user");
                });
#pragma warning restore 612, 618
        }
    }
}
